config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('goods.urls', namespace='goods')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from goods.apps import GoodsConfig
from goods.views import IndexView, CategoryListView, ProductDetailView, ProductCreateView, \
    ProductUpdateView, \
    ProductDeleteView, BlogListView, ContactsView, BlogCreateView, BlogUpdateView, BlogDetailView, \
    BlogDeleteView, ProductListView

app_name = GoodsConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/', ProductListView.as_view(), name='product_list'),
    path('goods/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('goods/create', ProductCreateView.as_view(), name='product_create'),
    path('goods/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('goods/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('blog_list', BlogListView.as_view(), name='blog_list'),
    path('blog_view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('goods/blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('goods/blog_update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('goods/blog_delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

goods/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import models

from config import settings


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название')
    description = models.CharField(max_length=150, verbose_name='Описание')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


User = get_user_model()


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название')
    description = models.CharField(max_length=150, verbose_name='Описание')
    image = models.ImageField(upload_to='images/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    creation_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    last_change_date = models.DateField(auto_now=True, verbose_name='Дата последнего изменения')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='владелец')

    def current_version(self):
        return self.version_set.filter(is_current=True).first()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        permissions = [
            (
                'can_unpublish_product',
                'Can unpublish product',
            ),
            (
                'can_change_product_description',
                'Can change product description',
            ),
            (
                'can_change_product_category',
                'Can change product category',
            ),
        ]

    def assign_unpublish_permission(self, user):
        content_type = ContentType.objects.get_for_model(Product)
        permission = Permission.objects.get(
            codename="can_unpublish_product",
            content_type=content_type,
            defaults={
                'name': 'Can unpublish product',
                'content_type': content_type,
            }
        )
        user.user_permissions.add(permission)

    def assign_change_product_description(self, user):
        content_type = ContentType.objects.get_for_model(Product)
        permission = Permission.objects.get(
            codename="can_change_product_description",
            content_type=content_type,
            defaults={
                'name': 'Can unpublish product',
                'content_type': content_type,
            }
        )
        user.user_permissions.add(permission)

    def assign_change_product_category(self, user):
        content_type = ContentType.objects.get_for_model(Product)
        permission = Permission.objects.get(
            codename="can_change_product_category",
            content_type=content_type,
            defaults={
                'name': 'Can change product description',
                'content_type': content_type,
            }
        )
        user.user_permissions.add(permission)


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    body = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog_previews/')
    created_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_name = models.CharField(max_length=250, verbose_name='Название версии')
    version_number = models.CharField(max_length=10, verbose_name='Номер версии', unique=True, blank=True, null=True)
    is_current = models.BooleanField(default=True, verbose_name='Актуальна')

    def __str__(self):
        return f'{self.product} - {self.version_name} - {self.version_number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

goods/forms.py
from django import forms

from goods.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'category', 'price', 'is_published',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        prohibited_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман',
                            'полиция', 'радар']

        for word in prohibited_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f"Слово '{word}' недопустимо для использования в названии.")
        return cleaned_data

    def clean_description(self):
        prohibited_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман',
                            'полиция', 'радар']
        description = self.cleaned_data['description']
        for word in prohibited_words:
            if word in description.lower():
                raise forms.ValidationError(f"Слово '{word}' недопустимо для использования в описании.")
        return description


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

goods/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, TemplateView, DeleteView, DetailView

from goods.forms import VersionForm, ProductForm
from goods.models import Category, Product, Blog, Version
from goods.services import get_categories


class IndexView(TemplateView):      # Главная страница
    template_name = 'goods/index.html'
    extra_context = {
        'title': 'Магазин для фанатов кантри'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Category.objects.all()[:3]
        return context_data


class ContactsView(View):
    template_name = 'goods/contacts.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'title': 'Контакты'})

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f'{name} ({email}): {message}')

        return render(request, self.template_name, {'title': 'Контакты'})


class CategoryListView(ListView):   # Категории в главном выпадающем меню
    model = Category
    extra_context = {
        'title': 'Категории'
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = get_categories(self.object.pk)
        return context


class ProductListView(LoginRequiredMixin, ListView):   # Cписок товаров при нажатии "Открыть" в списке категорий
    model = Product

    # def get_queryset(self):
    #     return super().get_queryset().filter(
    #         category_id=self.kwargs.get('pk'),
    #         owner=self.request.user
    #     )

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category_pk'] = category_item.pk
        context_data['title'] = f'Категория с товарами {category_item.name}'
        return context_data


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'goods/product_detail.html'
    context_object_name = 'product'

    def product_detail_view(request, product_id):
        product = Product.objects.get(pk=product_id)
        versions = product.get_versions()  # Получаем все версии продукта
        context = {
            'product': product,
            'versions': versions,  # Передаем версии продукта в контекст
        }
        return render(request, 'product_list.html', context)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('goods:index')

    def test_func(self):
        return self.request.user.is_authenticated  # Метод для определения авторизации пользователя

    def handle_no_permission(self):
        return LoginView.as_view(template_name='users/login.html')(self.request)  # Метод для возврата пользователя
        # на страницу авторизации при попытке доступа без авторизации


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = ['goods.can_unpublish_product', 'goods.can_change_product_description', 'goods.can_change_product_category']

    def test_func(self):
        return self.request.user.is_authenticated  # Метод для определения авторизации пользователя

    def handle_no_permission(self):
        return LoginView.as_view(template_name='users/login.html')(self.request)  # Метод для возврата пользователя
        # на страницу авторизации при попытке доступа без авторизации

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('goods:product_update', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    successful_url = reverse_lazy('goods:contacts')

    def test_func(self):
        return self.request.user.is_authenticated  # Метод для определения авторизации пользователя

    def handle_no_permission(self):
        return LoginView.as_view(template_name='users/login.html')(self.request)  # Метод для возврата пользователя
        # на страницу авторизации при попытке доступа без авторизации


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'preview',)
    success_url = reverse_lazy('goods:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'preview',)

    # success_url = reverse_lazy('goods:blog_view')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('goods:blog_view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('goods:blog_list')

goods/templates/goods/1goods.html
{% extends 'goods/base.html' %}
{% load my tags %}
{% block content%}
    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top"
                         src="{{ object.image|mymedia }}#"
                         alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">{{ object.name|title }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

goods/templates/goods/blog_confirm_delete.html
{% extends 'goods/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить статью "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'goods:blog_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

goods/templates/goods/blog_detail.html
{% extends 'goods/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Статья "{{ object.title }}" ({{ object.slug }})
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.body }}
                    </p>

                </div>
                <div class="card-footer"></div>
                    Просмотры: {{ object.views_count }}
            </div>
        </div>
        <div class="col-6">
            <img src="/media/{{ object.preview }}"/>
        </div>
    </div>
</div>
{% endblock %}

goods/templates/goods/blog_form.html
{% extends 'goods/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        {% if object %}
                        Редактирование записи
                        {% else %}
                        Создание записи
                        {% endif %}
                    </h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

goods/templates/goods/categories.html
{% extends 'goods/base.html' %}

{% block content%}
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">{{ object.name }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'goods:category_goods' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Открыть</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

goods/templates/goods/category_detail.html
{% extends 'goods/base.html' %}
{% block content%}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'goods:product_create' %}">Добавить продукт</a>
</div>
<div class="row">
    {% for object in product_items %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">{{ object.name }}</p>
                <p class="card-text">{{ object.description|truncatechars:100 }}</p>
                <p class="card-text">Версия: {{ object.current_version.version_number }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'goods:product_detail' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Открыть</a>
                        <a href="{% url 'goods:product_update' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Редактировать</a>
                        <a href="{% url 'goods:product_delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Удалить</a>
                    </div>
                </div>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

goods/templates/goods/category_list.html
{% extends 'goods/base.html' %}

{% block content%}
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">{{ object.name }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'goods:product_list' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Открыть</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

goods/templates/goods/contacts.html
{% extends 'goods/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Мы всегда рады обратной связи</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ZIP</td>
                            <td>90210</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Beverly Hills</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Введите сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

goods/templates/goods/goods.html
{% extends 'goods/base.html' %}
{% load my tags %}
{% block content%}
    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top"
                         src="{{ object.image|mymedia }}#"
                         alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">{{ object.name|title }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

goods/templates/goods/index.html
{% extends 'goods/base.html' %}
{% block content%}
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">{{ object.name }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'goods:product_list' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Открыть</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

goods/templates/goods/product_confirm_delete.html
{% extends 'goods/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт "{{ object.name }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'goods:index' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

goods/templates/goods/product_form.html
{% extends 'goods/base.html' %}

{% block content %}
<form method="post" class="uniForm">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    {% if object %}
                    Редактирование продукта
                    {% else %}
                    Добавление продукта
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Добавить
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
        {% if perms.goods.change_product %}
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Версии
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</form>
{% endblock %}

goods/templates/goods/product_list.html
{% extends 'goods/base.html' %}
{% block content%}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'goods:product_create' %}">Добавить продукт</a>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">{{ object.name }}</p>
                <p class="card-text">{{ object.description|truncatechars:100 }}</p>
                <p class="card-text">Версия: {{ object.current_version.version_number }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'goods:product_detail' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Открыть</a>
                        <a href="{% url 'goods:product_update' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Редактировать</a>
                        <a href="{% url 'goods:product_delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Удалить</a>
                    </div>
                </div>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

goods/templates/goods/products.html
{% extends 'goods/base.html' %}

{% block content%}
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">{{ object.name }}</p>
                <p class="card-text">{{ object.description|truncatechars:100 }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'goods:product' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Открыть</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}